#ifndef WEATHER_REGION_DATA_GLSL
#define WEATHER_REGION_DATA_GLSL

layout(std140) uniform WeatherRegionData {
    float u_cloudCoverageNorth;
    vec3  u_cloudColorNorth;
    vec3  u_cloudTopColorNorth;
    vec3  u_cloudShadowColorNorth;
    float u_cloudAltitudeNorth;
    float u_cloudDensityNorth;
    float u_cloudShadeStrengthNorth;
    float u_cloudRimLightStrengthNorth;
    float u_cloudAmbientOcclusionStrengthNorth;
    float u_cloudBrightnessMultiplierNorth;
    float u_cloudToonBandsNorth;
    float u_cloudDensityNoiseScaleNorth;
    float u_cloudNoiseWarpStrengthNorth;
    float u_cloudCoverageBiasNorth;
    float u_cloudSilhouetteSoftnessNorth;

    float u_cloudCoverageNortheast;
    vec3  u_cloudColorNortheast;
    vec3  u_cloudTopColorNortheast;
    vec3  u_cloudShadowColorNortheast;
    float u_cloudAltitudeNortheast;
    float u_cloudDensityNortheast;
    float u_cloudShadeStrengthNortheast;
    float u_cloudRimLightStrengthNortheast;
    float u_cloudAmbientOcclusionStrengthNortheast;
    float u_cloudBrightnessMultiplierNortheast;
    float u_cloudToonBandsNortheast;
    float u_cloudDensityNoiseScaleNortheast;
    float u_cloudNoiseWarpStrengthNortheast;
    float u_cloudCoverageBiasNortheast;
    float u_cloudSilhouetteSoftnessNortheast;

    float u_cloudCoverageEast;
    vec3  u_cloudColorEast;
    vec3  u_cloudTopColorEast;
    vec3  u_cloudShadowColorEast;
    float u_cloudAltitudeEast;
    float u_cloudDensityEast;
    float u_cloudShadeStrengthEast;
    float u_cloudRimLightStrengthEast;
    float u_cloudAmbientOcclusionStrengthEast;
    float u_cloudBrightnessMultiplierEast;
    float u_cloudToonBandsEast;
    float u_cloudDensityNoiseScaleEast;
    float u_cloudNoiseWarpStrengthEast;
    float u_cloudCoverageBiasEast;
    float u_cloudSilhouetteSoftnessEast;

    float u_cloudCoverageSoutheast;
    vec3  u_cloudColorSoutheast;
    vec3  u_cloudTopColorSoutheast;
    vec3  u_cloudShadowColorSoutheast;
    float u_cloudAltitudeSoutheast;
    float u_cloudDensitySoutheast;
    float u_cloudShadeStrengthSoutheast;
    float u_cloudRimLightStrengthSoutheast;
    float u_cloudAmbientOcclusionStrengthSoutheast;
    float u_cloudBrightnessMultiplierSoutheast;
    float u_cloudToonBandsSoutheast;
    float u_cloudDensityNoiseScaleSoutheast;
    float u_cloudNoiseWarpStrengthSoutheast;
    float u_cloudCoverageBiasSoutheast;
    float u_cloudSilhouetteSoftnessSoutheast;

    float u_cloudCoverageSouth;
    vec3  u_cloudColorSouth;
    vec3  u_cloudTopColorSouth;
    vec3  u_cloudShadowColorSouth;
    float u_cloudAltitudeSouth;
    float u_cloudDensitySouth;
    float u_cloudShadeStrengthSouth;
    float u_cloudRimLightStrengthSouth;
    float u_cloudAmbientOcclusionStrengthSouth;
    float u_cloudBrightnessMultiplierSouth;
    float u_cloudToonBandsSouth;
    float u_cloudDensityNoiseScaleSouth;
    float u_cloudNoiseWarpStrengthSouth;
    float u_cloudCoverageBiasSouth;
    float u_cloudSilhouetteSoftnessSouth;

    float u_cloudCoverageSouthwest;
    vec3  u_cloudColorSouthwest;
    vec3  u_cloudTopColorSouthwest;
    vec3  u_cloudShadowColorSouthwest;
    float u_cloudAltitudeSouthwest;
    float u_cloudDensitySouthwest;
    float u_cloudShadeStrengthSouthwest;
    float u_cloudRimLightStrengthSouthwest;
    float u_cloudAmbientOcclusionStrengthSouthwest;
    float u_cloudBrightnessMultiplierSouthwest;
    float u_cloudToonBandsSouthwest;
    float u_cloudDensityNoiseScaleSouthwest;
    float u_cloudNoiseWarpStrengthSouthwest;
    float u_cloudCoverageBiasSouthwest;
    float u_cloudSilhouetteSoftnessSouthwest;

    float u_cloudCoverageWest;
    vec3  u_cloudColorWest;
    vec3  u_cloudTopColorWest;
    vec3  u_cloudShadowColorWest;
    float u_cloudAltitudeWest;
    float u_cloudDensityWest;
    float u_cloudShadeStrengthWest;
    float u_cloudRimLightStrengthWest;
    float u_cloudAmbientOcclusionStrengthWest;
    float u_cloudBrightnessMultiplierWest;
    float u_cloudToonBandsWest;
    float u_cloudDensityNoiseScaleWest;
    float u_cloudNoiseWarpStrengthWest;
    float u_cloudCoverageBiasWest;
    float u_cloudSilhouetteSoftnessWest;

    float u_cloudCoverageNorthwest;
    vec3  u_cloudColorNorthwest;
    vec3  u_cloudTopColorNorthwest;
    vec3  u_cloudShadowColorNorthwest;
    float u_cloudAltitudeNorthwest;
    float u_cloudDensityNorthwest;
    float u_cloudShadeStrengthNorthwest;
    float u_cloudRimLightStrengthNorthwest;
    float u_cloudAmbientOcclusionStrengthNorthwest;
    float u_cloudBrightnessMultiplierNorthwest;
    float u_cloudToonBandsNorthwest;
    float u_cloudDensityNoiseScaleNorthwest;
    float u_cloudNoiseWarpStrengthNorthwest;
    float u_cloudCoverageBiasNorthwest;
    float u_cloudSilhouetteSoftnessNorthwest;
};

#endif